### ISSUE TITLE
很好，很强大，支持

### ISSUE THREAD

**Issue by weaming** [shibingli/webconsole#1]

**Comment by shibingli** [comment]
@weaming  感谢支持，希望能帮到大家。

**Comment by weaming** [comment]
有个快捷键 Ctrl+W，在shell里是个删除，但是在浏览器里会关闭标签，这个能否提前捕捉。

**Comment by shibingli** [comment]
@weaming 理论上浏览器的快捷键的优先级是高于应用的。你可以在term.js里面定义一个自己的快捷键试一下。我明天找个环境试试一下，再给你答案。

**Comment by shibingli** [comment]
@weaming    我使用Chrome，使用Ctrl + w  可以实现删除的功能，没有被浏览器劫持，你用的是什么浏览器？

**Comment by weaming** [comment]
@shibingli Chrome49

**Comment by shibingli** [comment]
@weaming  我找了几个人的 Chrome 49 都没有问题，你的操作系统是什么？我这边全是 Mac，不知道你是不是Windows？

**Comment by weaming** [comment]
windows7

**Comment by shibingli** [comment]
已知问题已修复，谢谢！
