### ISSUE TITLE
想单独执行某一个命令怎么执行?

### ISSUE THREAD

**Issue by shuyabin** [shibingli/webconsole#10]
大腿你好: 
 我想单独执行这个命令..不是通过终端输入的..应该怎么执行的?
![image](https://cloud.githubusercontent.com/assets/14884581/21078076/c5f93710-bf9c-11e6-88e3-5ef2d586da9a.png)

**Comment by shibingli** [comment]
什么意思？

**Comment by shibingli** [comment]
1、可以直接操作websocket来处理；2、直接操作Golang ssh库。
