### ISSUE TITLE
docker build不能通过

### ISSUE THREAD

**Issue by learn0208** [shibingli/webconsole#11]
![image](https://cloud.githubusercontent.com/assets/2122179/21168343/330cec5e-c1ee-11e6-866f-985b0d7b8c55.png)

**Comment by shibingli** [comment]
这个得根据Docker环境的实际情况，改一下Dockerfile。155122504可以直接加我的QQ，我给你看一下。

**Comment by learn0208** [comment]
@shibingli 问题解决了，是因为我代码没有拉全，谢谢了

**Comment by shibingli** [comment]
感谢对本项目的支持。
