### ISSUE TITLE
执行apibox start就会遇到如下问题 strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by qianguozheng** [shibingli/webconsole#12]
strconv.ParseInt: parsing "": invalid syntax

**Comment by qianguozheng** [comment]
找到问题了log/apibox.pid为空，导致`func (a *Apibox) Start() error` 这个函数种a.GetPID这个函数没有读取到pid 返回错误，导致程序退出。我在Ubuntu/CentOS都遇到了这个问题。

提议： 修改启动检查机制
改为： 退出时删除pid文件，异常退出时也删除。

**Comment by shibingli** [comment]
@qianguozheng  接受建议，待优化后发布。

**Comment by qianguozheng** [comment]
@shibingli 要不，咱讨论个方案，我来提交PR?

**Comment by shibingli** [comment]
@qianguozheng 没问题，欢迎参与。
