### ISSUE TITLE
golang的ssh支持Tab键 自动补全功能吗？

### ISSUE THREAD

**Issue by qianguozheng** [shibingli/webconsole#13]
ssh软件是支持这个功能的，不知道golang的ssh是否支持此功能，如何设置？

**Comment by shibingli** [comment]
webconsole是采用他ssh+websocket协议，关于SSH服务本身或个性化配置全是系统的功能。

**Comment by qianguozheng** [comment]
@shibingli 我用系统里面的ssh登陆到设备上是支持tab键自动补全的， 但是用webconsole就不行， 我单独实现golang的ssh连接也是不可以，问题可能出现在客户端上。

**Comment by shibingli** [comment]
@qianguozheng  我稍后再看一下，年底了比较忙，可能稍微晚点给出回复，谢谢。
