### ISSUE TITLE
命令中文问题

### ISSUE THREAD

**Issue by denglixing** [shibingli/webconsole#14]
通过xterm输入中文，例如cat xxx.log|grep "用户未登陆",服务器返回一堆感觉是ls /的东西

{"data":"g"}
{"data":"rep \"\u0007\u0007\u0007\u0008\u0008\u0008\u0008\u0008\u0008\u001b[K\r(arg: 1) \u001b[K"}
{"data":"\u0008\u0008\u00087) \r\u001b]0;root@fe38d2d32cb4: /xxx/package\u0007root@fe38d2d32cb4:/xxx/package# \u0007"}

然后控制台都是一些目录名

**Comment by shibingli** [comment]
我们这边用的term.js，暂时还没有切换到 xterm.js 。不过内部正在测试xterm.js，下一个大更新就会用xterm.js来做了。

**Comment by shibingli** [comment]
@denglixing   今天晚上我试着升级了一下xterm，你可以试试了。

**Comment by sbilly** [comment]
支持中文输入和显示吗？

**Comment by shibingli** [comment]
@sbilly   xterm.js 中文输入没有问题，但是输出我还在调试，目前看显示的时候还是有问题的。

**Comment by shibingli** [comment]
@sbilly 你可以试试看看，常见的中文应该没有问题。
