### ISSUE TITLE
这个go1.8.linux-amd64.tar.gz放到hub不合适吧，下载都费劲

### ISSUE THREAD

**Issue by ljw4010** [shibingli/webconsole#15]
RT

**Comment by shibingli** [comment]
主要是配合脚本用，国内很多地方无法正常下载，所以也是综合各种情况，提供了一个。

**Comment by ljw4010** [comment]
远虑啊，但我觉得可以单独存放一个repository，我觉得大部分gopher 应该都装有go了，不需要再下，也方便快速clone webconsole。

**Comment by shibingli** [comment]
嗯，你的意见不错，看看下次更新的时候我处理一下。
