### ISSUE TITLE
ws 403   ?   ( 浏览器chome 50+)

### ISSUE THREAD

**Issue by ljw4010** [shibingli/webconsole#16]
Request URL:ws://XXXXXXXXXXXXXX/console/sshws/4AnM1ZFyEabNmWfmiklO6XqevNea7m7Zsv419uNtt3Ee?cols=125&rows=12
Request Method:GET
Status Code:403 Forbidden

**Comment by shibingli** [comment]
将你的访问域名或者IP添加到白名单。说明里有介绍。
