### ISSUE TITLE
WebSocket connection to 'ws://xxxxxxxxxxxx?cols=87&rows=39' failed: Could not decode a text frame as UTF-8.

### ISSUE THREAD

**Issue by ljw4010** [shibingli/webconsole#17]
访问一次后退出后就会报下面的错误，
WebSocket connection to 'ws://xxxxxxxxxxxx?cols=87&rows=39' failed: Could not decode a text frame as UTF-8.
 Failed to parse SourceMap: http://xxxxxxxxxxxx/console/main/index.js.map
Failed to get text for stylesheet 3348.21: No style sheet with given id found

**Comment by shibingli** [comment]
宿主操作系统版本、远端操作系统版本、浏览器版本都是什么？

**Comment by shibingli** [comment]
term都跑了什么程序？

**Comment by shibingli** [comment]
时间过久，无人应答。

**Comment by ljw4010** [comment]
您好，抱歉最近较忙，只有周末恢复下：
**宿主操作系统版本、远端操作系统版本、浏览器版本都是什么？**
宿主机：win7
远端系统：centos6.5
浏览器：谷歌50+
现象：第一次登陆后，执行一些常用命令，退出或者ctrl+g  再次登录 浏览器就会有上述错误
