### ISSUE TITLE
运行了build.sh文件，为什么没有bin目录生成？

### ISSUE THREAD

**Issue by zteBill** [shibingli/webconsole#18]
@shibingli

**Comment by shibingli** [comment]
安装 Go 了么？

2017.03.14

修证:

    1、修证 wss 协议适配 BUG

更新：
    1、删除根目录 golang 程序包。如果运行脚本，请自行下载对应 golang 包（go1.8.linux-amd64.tar.gz）放置根目录。

**Comment by zteBill** [comment]
安装了 不过是go1.7.3版本的

**Comment by shibingli** [comment]
@zteBill  有报错么？

**Comment by shibingli** [comment]
@zteBill  把信息贴出来。

**Comment by shibingli** [comment]
@zteBill   为了大家方便部署，我更新了 README 请参考。

**Comment by zteBill** [comment]
按照你更新的README试了一下  还是没有bin生成  也没有什么报错

**Comment by zteBill** [comment]
`
root@zxin10-desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole/src/apibox.club/apibox# go install
apibox.go:13:2: cannot find package "apibox.club/utils" in any of:
        /usr/local/go/src/apibox.club/utils (from $GOROOT)
        /opt/gopath/src/apibox.club/utils (from $GOPATH)
apibox.go:14:2: cannot find package "apibox.club/website" in any of:
        /usr/local/go/src/apibox.club/website (from $GOROOT)
        /opt/gopath/src/apibox.club/website (from $GOPATH)
root@zxin10-desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole/src/apibox.club/apibox# GOPATH=^C
root@zxin10-desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole/src/apibox.club/apibox# GOPATH=/opt/gopath/src/github.com/webconsole_demo/webconsole go install
root@zxin10-desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole/src/apibox.club/apibox# cd ..
`

**Comment by zteBill** [comment]
> root@zxin10desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole/src/apibox.club/apibox# GOPATH=/opt/gopath/src/github.com/webconsole_demo/webconsole go install
root@zxin10desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole/src/apibox.club/apibox# cd ..
