### ISSUE TITLE
运行所有部署环节，并且没有报错，但是并没有bin目录生成

### ISSUE THREAD

**Issue by zteBill** [shibingli/webconsole#19]
root@zxin10-desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole# ./build.sh

==> Golang is already installed.

==> Please run the /opt/gopath/src/github.com/webconsole_demo/webconsole/bin/apibox.

root@zxin10-desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole# ll
total 76
drwxr-xr-x 9 root root  4096 4月  20 01:11 ./
drwxr-xr-x 3 root root  4096 4月  20 01:01 ../
-rwxr-xr-x 1 root root   689 4月  20 01:08 build.sh*
drwxr-xr-x 2 root root  4096 4月  20 01:08 conf/
-rw-r--r-- 1 root root   179 4月  20 01:08 Dockerfile
drwxr-xr-x 9 root root  4096 4月  20 01:08 .git/
-rw-r--r-- 1 root root   261 4月  20 01:08 .gitignore
-rw-r--r-- 1 root root  1065 4月  20 01:08 .gitmodules
-rw-r--r-- 1 root root 10721 4月  20 01:08 LICENSE
drwxr-xr-x 3 root root  4096 4月  20 01:11 pkg/
-rw-r--r-- 1 root root  8599 4月  20 01:08 README.md
drwxr-xr-x 5 root root  4096 4月  20 01:08 src/
drwxr-xr-x 4 root root  4096 4月  20 01:08 static/
drwxr-xr-x 3 root root  4096 4月  20 01:08 template/
drwxr-xr-x 2 root root  4096 4月  20 01:08 .vscode/

**Comment by zteBill** [comment]
root@zxin10-desktop:/opt/gopath/src/github.com/webconsole_demo/webconsole/src/apibox.club/apibox# go run apibox.go start
apibox.go:13:2: cannot find package "apibox.club/utils" in any of:
        /usr/local/go/src/apibox.club/utils (from $GOROOT)
        /opt/gopath/src/apibox.club/utils (from $GOPATH)
apibox.go:14:2: cannot find package "apibox.club/website" in any of:
        /usr/local/go/src/apibox.club/website (from $GOROOT)
        /opt/gopath/src/apibox.club/website (from $GOPATH)

**Comment by zteBill** [comment]
开发环境运行，请帮忙看看怎么在开发环境运行呢？ 谢谢！
/tmp/apiboxStartgo start
GOROOT=/opt/go/go1.7.3
GOPATH=/opt/gopath:/opt/gopath/src/github.com/webconsole_demo/webconsole
/opt/go/go1.7.3/bin/go build -o /tmp/apiboxStartgo github.com/webconsole_demo/webconsole/src/apibox.club/apibox
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c1a1b]

**Comment by shibingli** [comment]
请按照README的部署方式进行操作，谢谢。
