### ISSUE TITLE
不支持vim

### ISSUE THREAD

**Issue by yamateh** [shibingli/webconsole#2]
不会go不过在努力学习你的代码

**Comment by shibingli** [comment]
你的浏览器和VIM版本是多少？我在本地测试VIM没有问题。

**Comment by yamateh** [comment]
chrome 49.0.2623.112 
vim 7.4
`WebSocket connection to ''cols=150&rows=30' failed: Could not decode a text frame as UTF-8.`

**Comment by shibingli** [comment]
@yamateh   更新一下，你可以试试，谢谢！

**Comment by shibingli** [comment]
1.2 更新，已经修证 VIM 问题。

**Comment by pytimer** [comment]
Hi, @shibingli 

I use webconsole to connect my centos7.4 pc, it works well for me.

Now i want to write a websocket to connect docker container, i have the `vim` problem, like this issue.

Can you tell me what should i do? thanks.
