### ISSUE TITLE
还是请教几个问题，谢谢

### ISSUE THREAD

**Issue by zteBill** [shibingli/webconsole#20]
1、下载 go1.8.1.linux-amd64.tar.gz
2、tar zxvf go1.8.1.linux-amd64.tar.gz -C /usr/local
3、echo 'export PATH="/usr/local/go/bin:$PATH"' >> /etc/profile
4、source /etc/profile
这部分是安装go  我现在环境是已经安装了go的，而且也是开发了几个go实例  所以go环境没有问题
5、cd /opt && git clone --recurse-submodules https://github.com/shibingli/webconsole.git && cd webconsole && git submodule update --init --recursive
6、cd /opt/webconsole/src/apibox.club/apibox
7、GOPATH=/opt/webconsole go install
这部分只不过是获取代码 和 更新子模块 
后面GOPATH我也是按照我自己的代码路径来的   为啥什么都没有返回 也没有报错  也没有bin目录产生？
还有一个问题  请问程序在开发环境怎么搭建运行？

谢谢  麻烦了 ~
@shibingli

**Comment by shibingli** [comment]
开发环境用的是vscode，Go版本为1.8，操作系统为 ubuntu 16.04，GIT目录即为项目目录。

你这种情况我真没有碰到过，方便的话，你可以加我一下QQ：155122504，或者截一个动态图给我。

**Comment by shibingli** [comment]
无应答，关闭。
