### ISSUE TITLE
通过nginx转发问题

### ISSUE THREAD

**Issue by datacampus** [shibingli/webconsole#24]
请教下，我想通过nginx进行连接，webconsole把fcgi设置为true，正常启动，那么nginx中应该怎么设置呢，现在我是可以看到webconsole的初始化界面，但是当我连接其他服务器时，会报500错误，并且日志中没有详细信息,界面报：WebSocket connection to 'ws://192.168.0.11:8081/console/sshws/TMs0RynNtQloNKDBksDp8krEE3-Gj6S3nq4a1tYsxMlK6MrDiRs7inkYUQa4Mw==?cols=149&rows=15' failed: Error during WebSocket handshake: Unexpected response code: 500
 nginx中的设置为：
`
server {
    listen 8081;
    server_name localhost;

 location / {
            fastcgi_pass  192.168.0.11:8080;
           include        fastcgi_params;

}

}
`

**Comment by shibingli** [comment]
请将Nginx网关地址加入到域名白名单，谢谢。
