### ISSUE TITLE
cat 一个大文件,或者more一个大文件并持续查看，连接自动断开...

### ISSUE THREAD

**Issue by AEGQ** [shibingli/webconsole#25]

**Comment by ljw4010** [comment]
我也遇到过好多次

**Comment by AEGQ** [comment]
@ljw4010 

我的环境，f12看到的报错信息是这样：

     WebSocket connection to 'ws://localhost:8080/console/sshws/javcdNUtHeldA0te9u5qbTWwLFHtyTzOtiIFKA==?cols=113&rows=46' failed: Could not decode a text frame as UTF-8.

但事实上我已经设置了语言支持utf-8，而且vim打开是没问题的(ps: vim上下翻页也会报上面的错，并退出)

**Comment by shibingli** [comment]
已经收录了问题，正在处理。

**Comment by AEGQ** [comment]
@shibingli  谢谢回复 :)

**Cat 问题**

修改: 
![2017-07-17_160201](https://user-images.githubusercontent.com/16302289/28260027-d265e442-6b0b-11e7-9400-e1373b050d72.png)

效果:
可正常显示原大文件的部分内容,而其余内容Valid验证非UTF-8格式。

参考:
https://godoc.org/github.com/gorilla/websocket#hdr-Data_Messages

**Comment by shibingli** [comment]
@AEGQ   不错，如果您能参与到这个项目里来就更好了！

**Comment by AEGQ** [comment]
@shibingli  谢谢 :)

如果有验证可用的修改，一定第一时间提交PR。
