### ISSUE TITLE
如何终止控制台里启动的进程ctrl+c/ctrl+z

### ISSUE THREAD

**Issue by 93425129** [shibingli/webconsole#28]
请问怎么停止 tailf 
ctrl+c不起效果
目前发现是的是使用ctrl+z，但是是stopped到后端执行了。 进程没有被杀死

**Comment by 603627156** [comment]
部署完成怎么使用，发个文档嘛！谢谢  603627156@qq.com

**Comment by shibingli** [comment]
其实这就是一个远程的SSH Web客户端，您平时怎么用Linux或类Unix类的终端，就怎么用这个工具，唯一不同的地方就是宿主机与被控主机可正常通信。大多数情况下，这个工具应用于有限的内网环境。



BRs
✉✉✉✉✉✉✉✉✉✉✉✉✉✉✉✉✉✉✉✉
史 丙 利 / Eric Shi
CO-Founder & CTO

北京中视广纳文化传播有限公司
地址：北京市朝阳区朗廷大厦B座 502室  邮编：100024
电话: 010-57019161   手机:18701575902
网址: http://www.ayerdudu.com/
