### ISSUE TITLE
在终端里面 为什么 复制粘贴的时候 显示2次？

### ISSUE THREAD

**Issue by hequan2017** [shibingli/webconsole#30]
在终端里面 为什么 复制粘贴的时候 显示2次？

**Comment by shibingli** [comment]
能说的详细一些么？系统环境，操作步骤等。

**Comment by hequan2017** [comment]
就是按照你的要求安装的，安装完       登陆之后    从别的地方复制粘贴命令过来，会显示两行，但是实际就是一行。

**Comment by 1032231418** [comment]
系统环境 Centos  6.5 X64    每次复制  都会重复两次

**Comment by shibingli** [comment]
目前采用chrome、firefox/Ubuntu、CentOS6、7 测试没有出现。

**Comment by gang929** [comment]
才clone出来的，完全按步骤安装出来， ctr+ins shift+ins， 拷贝粘贴，就是会多显示一次， 回车后，看到实际只输入了一次
浏览器：firefox/360都有这样的问题

**Comment by gang929** [comment]
chrome浏览器同样问题  
鼠标右键 拷贝，再右键粘贴，同样显示重复

**Comment by njustyangkai** [comment]
我已经解决了这个问题，想解决，可以单独找我

**Comment by shibingli** [comment]
@njustyangkai   你好，如果你愿意，可以将此BUG提交到Github上，分享给大家。

**Comment by njustyangkai** [comment]
@shibingli 可以的，我提交到哪里呢？

**Comment by 1032231418** [comment]
@njustyangkai 提交给作者，他会合并，也可以提供一个Git 地址

**Comment by 1032231418** [comment]
@shibingli  (#^.^#)   期待新功能

**Comment by njustyangkai** [comment]
@shibingli 好的，但是我需要晚上回家处理，因为公司有墙，你懂的，关注的童鞋，请耐心等待下~~

**Comment by njustyangkai** [comment]
@shibingli 我的浏览器版本是 IE11.0.56和Chrome65.0.3325.181（正式版本） （32 位），这两个浏览器经过我的修改后都没有问题

**Comment by njustyangkai** [comment]
@shibingli 不好意思，比较忙，忘了回复了，大家将这个[文件](https://github.com/shibingli/webconsole/blob/master/static/scripts/console.js)的205-207行注释掉试试：
![qq20180416-0](https://user-images.githubusercontent.com/20183284/38815807-5037987e-41c7-11e8-9131-01abf2b98cd4.png)

**Comment by shibingli** [comment]
@njustyangkai 厉害，改好后提交到上来吧，我来合并。

**Comment by shibingli** [comment]
目前在计划2.0的版本，只要不是致命问题，会跟随新版发布。
