### ISSUE TITLE
登录进去黑屏是什么问题呢?

### ISSUE THREAD

**Issue by zhoujia** [shibingli/webconsole#31]
我使用的是默认配置,远端是centos7的docker容器.进去之后, w 能看到client端已经ssh登录进来了.但是页面是一片黑,什么也不显示.是不是有某些默认配置项需要修改呢?
能在readme里说明下配置参数的意义吗?

**Comment by shibingli** [comment]
应该是白名单策略没有配置好，或者启用了jsonp．

后面更新会增加上说明，感谢支持．

**Comment by zhoujia** [comment]
把网关加入白名单确实解决了问题
