### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by goofusuper** [shibingli/webconsole#32]
Step 4 : RUN cd /go/src/apibox.club/apibox/ && go install -v
 ---> Running in 3c46820b1ce1
../utils/dbutils.go:5:2: no buildable Go source files in /go/src/github.com/go-sql-driver/mysql
../website/console.go:14:2: no buildable Go source files in /go/src/github.com/gorilla/websocket
../website/console.go:15:2: cannot find package "golang.org/x/crypto/ssh" in any of:
        /usr/local/go/src/golang.org/x/crypto/ssh (from $GOROOT)
        /go/src/golang.org/x/crypto/ssh (from $GOPATH)
../utils/utils.go:22:2: cannot find package "golang.org/x/text/encoding" in any of:
        /usr/local/go/src/golang.org/x/text/encoding (from $GOROOT)
        /go/src/golang.org/x/text/encoding (from $GOPATH)
../utils/utils.go:23:2: cannot find package "golang.org/x/text/encoding/japanese" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/japanese (from $GOROOT)
        /go/src/golang.org/x/text/encoding/japanese (from $GOPATH)
../utils/utils.go:24:2: cannot find package "golang.org/x/text/encoding/korean" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/korean (from $GOROOT)
        /go/src/golang.org/x/text/encoding/korean (from $GOPATH)
../utils/utils.go:25:2: cannot find package "golang.org/x/text/encoding/simplifiedchinese" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/simplifiedchinese (from $GOROOT)
        /go/src/golang.org/x/text/encoding/simplifiedchinese (from $GOPATH)
../utils/utils.go:26:2: cannot find package "golang.org/x/text/encoding/traditionalchinese" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/traditionalchinese (from $GOROOT)
        /go/src/golang.org/x/text/encoding/traditionalchinese (from $GOPATH)
../utils/utils.go:27:2: cannot find package "golang.org/x/text/encoding/unicode" in any of:
        /usr/local/go/src/golang.org/x/text/encoding/unicode (from $GOROOT)
        /go/src/golang.org/x/text/encoding/unicode (from $GOPATH)
../utils/utils.go:28:2: cannot find package "golang.org/x/text/transform" in any of:
        /usr/local/go/src/golang.org/x/text/transform (from $GOROOT)
        /go/src/golang.org/x/text/transform (from $GOPATH)

**Comment by shibingli** [comment]
应该是GIT没有关联子项目，请严格按照安装说明配置部署．
