### ISSUE TITLE
服务器响应403

### ISSUE THREAD

**Issue by ynhao** [shibingli/webconsole#36]
控制台输入账号密码后，在终端的页面js报错：WebSocket connection to 'ws://192.168.91.128:8080/console/sshws/g7CrqekJ-Q-Jljlgc67hu0zRldZdwi4R2estCxqTKw==?cols=125&rows=64' failed: Error during WebSocket handshake: Unexpected response code: 403，请问这是什么原因照成的呢？

**Comment by ynhao** [comment]
找到问题了，是因为没有添加服务器ip到white_list中从而被服务器拒绝掉了

**Comment by 603627156** [comment]
为什么我的登录进来什么都操作不了！？？？？？？

**Comment by shibingli** [comment]
@603627156   请描述一下具体流程。
