### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by ynhao** [shibingli/webconsole#38]
jsonp跨域提交post请求失败，服务端返回的json对象如下：
{
    "ok": true,
    "msg": "",
    "data": "/console/main/wkpe2VrDtSBXQwrWp8Es8px0ROjhjJh379Wb91WqE6wx"
}
该json对象不能被js处理从而报错“Uncaught SyntaxError: Unexpected token :”,
请问我该怎么处理此类问题？

**Comment by shibingli** [comment]
跨域的话，需要把配置文件里的jsonp配置为true.
