### ISSUE TITLE
按照步骤install的时候报错了

### ISSUE THREAD

**Issue by sinnerliu** [shibingli/webconsole#39]
clone的是最新的master代码；
remote: Compressing objects: 100% (43/43), done.
remote: Total 19017 (delta 24), reused 35 (delta 18), pack-reused 18955
Receiving objects: 100% (19017/19017), 7.83 MiB | 1.56 MiB/s, done.
Resolving deltas: 100% (13553/13553), done.
Submodule path 'src/golang.org/x/tools': checked out '8b178a93c1f5b5c8f4e36cd6bd64e0d5bf0ee180'
[root@centos7 webconsole]# ls
conf  Dockerfile  LICENSE  README.md  src  static  template
[root@centos7 webconsole]# cd /opt/webconsole/src/apibox.club/apibox
[root@centos7 apibox]# GOPATH=/opt/webconsole go install
# apibox.club/website
../website/console.go:35: undefined: ssh.InsecureIgnoreHostKey

**Comment by shibingli** [comment]
这个是Git Submodule没有下载完全，请重新下载。
