### ISSUE TITLE
docker部署一直访问失败

### ISSUE THREAD

**Issue by vcdfretgb** [shibingli/webconsole#40]
你好，请问一下我用的是v2版本的那个branch，通过docker build的镜像去docker run之后启动是成功的，登录页面也能访问，但是在页面上调用http://10.0.0.151:32771/console/chksshdaddr 接口的时候一直都是404，点击登录按钮调用的http://10.0.0.151:32771/console/login 接口也一直都是404，不是很清楚原因在哪里。
  然后通过docker pull了两个版本的镜像分别是shibingli/webconsole:latest和shibingli/webconsole:v2，v2的镜像也是同样的问题，而latest则是发现登录成功了，但是http://10.0.0.151:32772/console/sshws/iTigtW5fH3eaftrV03UfI7wMRH5e-Ve-QGY=?cols=145&rows=9 这个websocket报了403，所以没法操作。conf.json下的cors_white_list也已经添加并重启了容器 仍然是403

**Comment by shibingli** [comment]
V2的还没有发布，请使用V1.
