### ISSUE TITLE
webconsole没有生成

### ISSUE THREAD

**Issue by damondengxin** [shibingli/webconsole#41]
一，centos 7.2 
1，yum -y install go
2, go版本
[root@devel apibox]# go version
go version go1.8.3 linux/amd64
二，生成webconsole步骤如下
1，ssh.InsecureIgnoreHostKey报错
[root@devel apibox]# GOPATH=/root/webconsole go install
# apibox.club/website
../website/console.go:35: undefined: ssh.InsecureIgnoreHostKey

2，根据网上方案解决，
删除crypto
[root@devel apibox]# rm -rf /root/webconsole/src/golang.org/x/crypto
You have new mail in /var/spool/mail/root
[root@devel apibox]# cd /root/webconsole/src/golang.org/x/
重新下载crypto
[root@devel x]# git clone https://github.com/golang/crypto.git
Cloning into 'crypto'...
remote: Counting objects: 3984, done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 3984 (delta 9), reused 23 (delta 6), pack-reused 3919
Receiving objects: 100% (3984/3984), 2.95 MiB | 296.00 KiB/s, done.
Resolving deltas: 100% (2507/2507), done.
[root@devel x]# cd -
/root/webconsole/src/apibox.club/apibox
重新安装
[root@devel apibox]# GOPATH=/root/webconsole go install
结果没有
[root@devel apibox]# ll /root/webconsole/conf/
total 8
-rw-r--r-- 1 root root  889 Dec 11 09:25 conf.json
-rw-r--r-- 1 root root 3956 Dec 11 09:25 mime.types
不知道问题出在哪，盼回复，谢谢！

**Comment by shibingli** [comment]
把代码全阅删了，重新拉一下代码吧，代码没有拉全。
