### ISSUE TITLE
右边滚动条无法拖动

### ISSUE THREAD

**Issue by Jim-wiselike** [shibingli/webconsole#46]
版本最新版，只能通过鼠标滚轮，鼠标不能拖动呢！chrome版本 WIN 62.0.3202.94（正式版本）（64 位） 版本应该还算较新吧。。。

**Comment by njustyangkai** [comment]
我已经解决了这个问题，可以私下联系我

**Comment by Jim-wiselike** [comment]
本来就是开源项目，而且是Apache 2的license，提交开源吧，一起获利

2018-04-16 

吴衡敬上 



发件人：yangkai <notifications@github.com>
发送时间：2018-04-16 22:44
主题：Re: [shibingli/webconsole] 右边滚动条无法拖动 (#46)
收件人："shibingli/webconsole"<webconsole@noreply.github.com>
抄送："Jim-wiselike"<w._heng@163.com>,"Author"<author@noreply.github.com>

我已经解决了这个问题，可以私下联系我

**Comment by shibingli** [comment]
@njustyangkai  开源的好处就是让大家共享资源，让大家图个方便。如果你愿意就提交一下代码，我来做合并。
