### ISSUE TITLE
目前的登录感觉不够安全，及一些需求

### ISSUE THREAD

**Issue by kochTao** [shibingli/webconsole#51]
1. 目前每次请求的加密串都是通过IP,用户名与密码加密的，这样就会有一个问题，每次登录后只要有这个加密串不管在哪台物理机都可以随意登录，session是30分钟，没有试过30分过后这个key还可以登录否，希望多一些安全控制。
2.能否支持ssh_key 登录，目前只支持用户名密码登录，我这边是有自己修改通过ssh_key登录，希望大神能提供配置2种方式选择。
3.日志记录不会根据日期分割，必须重启API才可以。
4.审计功能，用户执行的命令记录。现在是有修改对websocket的输入进行记录，但是感觉比较low，希望webconsole能提供一个配置审计的功能。

**Comment by shibingli** [comment]
嗯，这些问题会在2.0版本修复和优化。
