### ISSUE TITLE
How to manage multiple machines through webconsole?

### ISSUE THREAD

**Issue by ping035627** [shibingli/webconsole#53]
Hi @shibingli , I want to access all the machines in the LAN through webconsole, how to manage multiple machines through webconsole? Thanks.
All the machines are in a local area network, only one machine can communicate with the outside network. I want to provide the function of Web terminal through this machine. Can this function be implemented through webconsole? Thanks.

**Comment by shibingli** [comment]
1、目前webconsole仅支持单个会话；
2、将webconsole部署到可以访问外网的机器上，然后通过外网地址就可以直接连到内网的机器上。
