### ISSUE TITLE
内部错误，请联系管理员（postmaster@apibox.club）。

### ISSUE THREAD

**Issue by guomaoqiu** [shibingli/webconsole#54]
请问我在得到了加密的en_addr 后通过浏览器访问登录 报错：
![image](https://user-images.githubusercontent.com/9714859/45877152-7db9ab00-bdcf-11e8-87b7-c4c5ea371d34.png)
服务器端没任何报错~ 求解决

**Comment by shibingli** [comment]
将服务器的IP和端口加入到白名单。

**Comment by riverzhang** [comment]
cc @shibingli 
将服务器的IP和端口加入到白名单。 
没明白什么意思。 我也遇到同样的问题。

**Comment by riverzhang** [comment]
[DEBUG] 2019/01/18 09:36:20 console.go 409 apibox.club/website.(*Console).ConsoleLogin [root rongs_123   2019-01-18 09:36:20]
[DEBUG] 2019/01/18 09:36:21 console.go 409 apibox.club/website.(*Console).ConsoleLogin [root rongs_123   2019-01-18 09:36:21]
[DEBUG] 2019/01/18 09:36:24 console.go 409 apibox.club/website.(*Console).ConsoleLogin [root rongs_123   2019-01-18 09:36:24]

**Comment by riverzhang** [comment]
[DEBUG] 2019/01/18 09:36:20 console.go 409 apibox.club/website.(*Console).ConsoleLogin [root rongs_123   2019-01-18 09:36:20]
[DEBUG] 2019/01/18 09:36:21 console.go 409 apibox.club/website.(*Console).ConsoleLogin [root 123   2019-01-18 09:36:21]
[DEBUG] 2019/01/18 09:36:24 console.go 409 apibox.club/website.(*Console).ConsoleLogin [root 123  2019-01-18 09:36:24]

**Comment by shibingli** [comment]
conf.json配置一下域的白名单

**Comment by dyb1296** [comment]
也是这个问题，不是很明白~~

**Comment by dyb1296** [comment]
可以详细说明一下吗

**Comment by shibingli** [comment]
将主机域名及端口添到加conf.json中的cors_white_list中。
