### ISSUE TITLE
超过一屏时，输入时总出现滚动条，看不到下面输入的内容

### ISSUE THREAD

**Issue by ssqf** [shibingli/webconsole#57]
超过一屏时，输入时总出现滚动条，看不到下面输入的内容
![image](https://user-images.githubusercontent.com/13485967/54071942-dc57e000-42ae-11e9-9175-04aac14043be.png)
![image](https://user-images.githubusercontent.com/13485967/54071958-0e694200-42af-11e9-889e-1adddffaf7b5.png)
![image](https://user-images.githubusercontent.com/13485967/54071963-1b863100-42af-11e9-8de5-056cf69041ea.png)

**Comment by shibingli** [comment]
看不到截图

**Comment by shibingli** [comment]
这个是可视区域计算问题，不同的浏览器可能有一些问题。这个版本计划暂停，后面会释放出来一个全新的版本。
