### ISSUE TITLE
自行编译中的问题，还有一些建议

### ISSUE THREAD

**Issue by jim3mar** [shibingli/webconsole#6]
* install.sh 脚本有问题，主要是go install的时候有问题，我把src下面的依赖全删了，然后重新go get ./... 后成功
* 既然已经用go1.6了，那建议用[godep](https://github.com/tools/godep)来管理依赖包，1.6已经支持了
* 横向的导航栏，其实可以改成纵向的，一般显示器都是宽屏的

> 都是一些建议，很不错的项目，我愿意参与，不过前端技术太渣。

**Comment by jim3mar** [comment]
后来有看了一下，依赖的问题是因为用了submodule，所以只要添加
```
git submodule update --init --recursive
```
即可

**Comment by shibingli** [comment]
@jim3mar   欢迎加入。由于这个项目比较小，最初只是一个小工具，依懒的库不是很多，所以就直接用GIT Submodule 管理了。
