### ISSUE TITLE
请问cors_white_list放通0.0.0.0该怎么配置呢

### ISSUE THREAD

**Issue by lifa1225** [shibingli/webconsole#64]
请问cors_white_list放通0.0.0.0该怎么配置呢？我配置了0.0.0.0:9099但是还是不生效。
![image](https://user-images.githubusercontent.com/59470742/79313740-61daa480-7f33-11ea-9ebb-d13ce7e96f6d.png)
![image](https://user-images.githubusercontent.com/59470742/79313774-6ef79380-7f33-11ea-801d-ea1bfb385655.png)

**Comment by shibingli** [comment]
可以代码中做一下处理，有相关的标记。
